#pragma once

#define DEBUG_RATE 10

#define FLAKE_COUNT 10000
#define FLAKE_MIN_DROP_SPEED 1.5
#define FLAKE_DAMPING_RATE 0.07

#define COUNTER_DECREMENT 0.5

#define CLIMAX_TOTAL_FORCE 1000

#define FINISH_FRAMES 240
